/*Write a function that returns balance for given account number.*/

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

CREATE OR REPLACE FUNCTION ACC_BAL

(ACCO_NO IN NUMBER)
RETURN NUMBER
AS
BAL ACCOUNT.BALANCE%TYPE;
BEGIN
	SELECT BALANCE INTO BAL FROM ACCOUNT WHERE ACC_NO = ACCO_NO ;
	RETURN BAL ;
END;
/

SET SERVEROUTPUT OFF
SET FEEDBACK ON
SET VERIFY ON