/*Write a trigger to insert the values into the NEWEMP table when the records are inserted into the EMP table.*/

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

CREATE OR REPLACE TRIGGER TRG_INS_BACKUP
BEFORE INSERT
ON EMP
FOR EACH ROW
BEGIN
	INSERT INTO NEWEMP(EMP_NO,SAL,DEPTNO,EMP_NAME) VALUES(:NEW.EMP_NO,:NEW.SAL,:NEW.DEPTNO,:NEW.EMP_NAME);
END;
/

SET SERVEROUTPUT OFF
SET FEEDBACK ON
SET VERIFY ON