/*Write a trigger that restricts the entry of record if salary is greater than Rs.50000.*/

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

CREATE OR REPLACE TRIGGER TRG_RESTRICT_SAL
BEFORE INSERT OR UPDATE
ON EMP
FOR EACH ROW
BEGIN
	IF :NEW.SAL > 50000 THEN
		RAISE_APPLICATION_ERROR(-20101,'RESTRICTED SALARY INPUT.');
	END IF;
END;
/

SET SERVEROUTPUT OFF
SET FEEDBACK ON
SET VERIFY ON