/* Write a program of mark sheet with displays the SEAT_NO, NAME OF STUDENT, marks 
of 5 subjects, total of 5 subjects and PER, also display the class of student
based on the value of PER. */

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

DECLARE 

	SEAT_NO 	 MARKSHEET.SEAT_NO%TYPE ;
	STUDENT_NAME 	 MARKSHEET.STUDENT_NAME%TYPE ;
	RDBMS_MARKS 	 MARKSHEET.RDBMS_MARKS%TYPE ;
	OS_MARKS	 MARKSHEET.OS_MARKS%TYPE ;
	DS_MARKS 	 MARKSHEET.DS_MARKS %TYPE ;
	JAVA_MARKS 	 MARKSHEET.JAVA_MARKS%TYPE ;
	PHP_MARKS 	 MARKSHEET.PHP_MARKS%TYPE ;
	TOTAL_MARKS 	 MARKSHEET.TOTAL_MARKS%TYPE ;
	PER	         MARKSHEET.PERCENTAGE%TYPE ;
	CLASS		 MARKSHEET.CLASS%TYPE ;

BEGIN

	SEAT_NO	         := &SEAT_NO ;
	STUDENT_NAME 	 := '&STUDENT_NAME' ;
	RDBMS_MARKS 	 := &RDBMS_MARKS ;
	OS_MARKS	 := &OS_MARKS ;
	DS_MARKS 	 := &DS_MARKS ;
	JAVA_MARKS 	 := &JAVA_MARKS ;
	PHP_MARKS 	 := &PHP_MARKS ;

	TOTAL_MARKS := RDBMS_MARKS + OS_MARKS + DS_MARKS + JAVA_MARKS + PHP_MARKS ;
	
	PER := TOTAL_MARKS/5 ;

	IF ( PER >= 70 ) THEN
		CLASS := 'DISTINCTION';
	ELSIF ( PER >= 60 AND PER < 70 ) THEN
		CLASS := 'FIRST CLASS';
	ELSIF ( PER >= 50 AND PER < 60 ) THEN
		CLASS := 'SECOND CLASS';
	ELSIF ( PER >= 40 AND PER < 50 ) THEN
		CLASS := 'PASS';
	ELSE 
		CLASS := 'FAIL';
	END IF;

	INSERT INTO MARKSHEET VALUES(SEAT_NO , STUDENT_NAME , RDBMS_MARKS , OS_MARKS , DS_MARKS , JAVA_MARKS , PHP_MARKS , TOTAL_MARKS , PER , CLASS );
	
END;
/

SET SERVEROUTPUT OFF
SET FEEDBACK ON
SET VERIFY ON

SELECT * FROM MARKSHEET ;
