-- Write a program that prints value 1 to 100 numbers using FOR LOOP.

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

DECLARE
	NO NUMBER := 1 ;
BEGIN
	FOR NO IN 1..100
	LOOP
	DBMS_OUTPUT.PUT(NO||' ');
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('');
END;
/

SET SERVEROUTPUT OFF
SET FEEDBACK ON
SET VERIFY ON