-- Write a program that prints value 1 to 100 number using LOOP Command.

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

DECLARE
	NO NUMBER := 1 ;
BEGIN
	LOOP
	EXIT WHEN NO = 101;
		DBMS_OUTPUT.PUT(NO||' ');
		NO := NO+1;
	END LOOP;
		DBMS_OUTPUT.PUT_LINE('');
END;
/

SET SERVEROUTPUT OFF
SET FEEDBACK ON
SET VERIFY ON