-- Write a program that prints value 1 to 100 number using WHILE LOOP Command.

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

DECLARE
	NO NUMBER := 1 ;
BEGIN
	WHILE NO <= 100
	LOOP
		DBMS_OUTPUT.PUT(NO||' ');
		NO := NO+1;
	END LOOP;
		DBMS_OUTPUT.PUT_LINE('');
END;
/

SET SERVEROUTPUT OFF
SET FEEDBACK ON
SET VERIFY ON