/*Write a simple procedure without any parameter that updates the values in the EMP table.*/

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

CREATE OR REPLACE PROCEDURE UPDATE_EMP
IS
BEGIN
	UPDATE EMP SET SAL = SAL+(SAL*0.20);
	DBMS_OUTPUT.PUT_LINE('SALARY UPDATED...');
END;
/


SET SERVEROUTPUT OFF
SET FEEDBACK ON
SET VERIFY ON