/*Write a PL/SQL block to show the name of employee for given employee number.*/

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

DECLARE

	E_ID NUMBER(4);
	E_NAME VARCHAR2(25);

BEGIN

	E_ID := &E_ID ;
	
	SELECT EMP_NAME INTO E_NAME FROM EMP WHERE EMP_ID = E_ID ;
	
	DBMS_OUTPUT.PUT_LINE('NAME OF EMPLOYEE IS '||E_NAME||'.');

END;
/

SET SERVEROUTPUT OFF
SET FEEDBACK ON
SET VERIFY ON
