/*Write a function that calculates the binary value for the given number.*/

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

CREATE OR REPLACE FUNCTION DEC2BIN
(N IN NUMBER)
RETURN NUMBER
AS
	BINVAL VARCHAR2(64);
	N2 NUMBER := N;
BEGIN
	WHILE(N2>0)LOOP
		BINVAL := MOD(N2,2)||BINVAL;
		N2	   := TRUNC(N2/2);
	END LOOP;
RETURN BINVAL;
END;
/

SET SERVEROUTPUT OFF
SET FEEDBACK ON
SET VERIFY ON